//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.29 at 02:53:13 PM MSD 
//


package org.m4water.server.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}waterpointId"/>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}inspector_name"/>
 *         &lt;element ref="{}inspectionQuestions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "waterpointId",
    "date",
    "inspectorName",
    "inspectionQuestions"
})
@XmlRootElement(name = "inspection")
public class Inspection {

    @XmlElement(required = true)
    protected String waterpointId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String date;
    @XmlElement(name = "inspectorName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String inspectorName;
    @XmlElement(required = true)
    protected InspectionQuestions inspectionQuestions;

    /**
     * Gets the value of the waterpointId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterpointId() {
        return waterpointId;
    }

    /**
     * Sets the value of the waterpointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterpointId(String value) {
        this.waterpointId = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the inspectorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspectorName() {
        return inspectorName;
    }

    /**
     * Sets the value of the inspectorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspectorName(String value) {
        this.inspectorName = value;
    }

    /**
     * Gets the value of the inspectionQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link InspectionQuestions }
     *     
     */
    public InspectionQuestions getInspectionQuestions() {
        return inspectionQuestions;
    }

    /**
     * Sets the value of the inspectionQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InspectionQuestions }
     *     
     */
    public void setInspectionQuestions(InspectionQuestions value) {
        this.inspectionQuestions = value;
    }

}
