//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 12:53:45 AM MSD 
//


package org.m4water.server.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}assignedUser"/>
 *         &lt;element ref="{}district"/>
 *         &lt;element ref="{}subcounty"/>
 *         &lt;element ref="{}village"/>
 *         &lt;element ref="{}sourceName"/>
 *         &lt;element ref="{}inspectorName"/>
 *         &lt;element ref="{}reportingDate"/>
 *         &lt;element ref="{}currentOwnership"/>
 *         &lt;element ref="{}typeOfManagement"/>
 *         &lt;element ref="{}isFunctional"/>
 *         &lt;element ref="{}reasonNonFunctional"/>
 *         &lt;element ref="{}daysNonFuntional"/>
 *         &lt;element ref="{}hasPreviousRepairs"/>
 *         &lt;element ref="{}lastRepairDate"/>
 *         &lt;element ref="{}hasMinorService"/>
 *         &lt;element ref="{}hasMajorService"/>
 *         &lt;element ref="{}dateLastRepair"/>
 *         &lt;element ref="{}isWucEstablished"/>
 *         &lt;element ref="{}isWucFunctional"/>
 *         &lt;element ref="{}isWucTrained"/>
 *         &lt;element ref="{}membersNumberWuc"/>
 *         &lt;element ref="{}womenNumberWuc"/>
 *         &lt;element ref="{}womenKeypositionsNumberWuc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assignedUser",
    "district",
    "subcounty",
    "village",
    "sourceName",
    "inspectorName",
    "reportingDate",
    "currentOwnership",
    "typeOfManagement",
    "isFunctional",
    "reasonNonFunctional",
    "daysNonFuntional",
    "hasPreviousRepairs",
    "lastRepairDate",
    "hasMinorService",
    "hasMajorService",
    "dateLastRepair",
    "isWucEstablished",
    "isWucFunctional",
    "isWucTrained",
    "membersNumberWuc",
    "womenNumberWuc",
    "womenKeypositionsNumberWuc"
})
@XmlRootElement(name = "Waterpoint")
public class Waterpoint {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String assignedUser;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String district;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String subcounty;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String village;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sourceName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String inspectorName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reportingDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String currentOwnership;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String typeOfManagement;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String isFunctional;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String reasonNonFunctional;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String daysNonFuntional;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hasPreviousRepairs;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String lastRepairDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hasMinorService;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String hasMajorService;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String dateLastRepair;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String isWucEstablished;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String isWucFunctional;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String isWucTrained;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String membersNumberWuc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String womenNumberWuc;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String womenKeypositionsNumberWuc;

    /**
     * Gets the value of the assignedUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedUser() {
        return assignedUser;
    }

    /**
     * Sets the value of the assignedUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedUser(String value) {
        this.assignedUser = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the subcounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcounty() {
        return subcounty;
    }

    /**
     * Sets the value of the subcounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcounty(String value) {
        this.subcounty = value;
    }

    /**
     * Gets the value of the village property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVillage() {
        return village;
    }

    /**
     * Sets the value of the village property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVillage(String value) {
        this.village = value;
    }

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the inspectorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInspectorName() {
        return inspectorName;
    }

    /**
     * Sets the value of the inspectorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInspectorName(String value) {
        this.inspectorName = value;
    }

    /**
     * Gets the value of the reportingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingDate() {
        return reportingDate;
    }

    /**
     * Sets the value of the reportingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingDate(String value) {
        this.reportingDate = value;
    }

    /**
     * Gets the value of the currentOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentOwnership() {
        return currentOwnership;
    }

    /**
     * Sets the value of the currentOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentOwnership(String value) {
        this.currentOwnership = value;
    }

    /**
     * Gets the value of the typeOfManagement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfManagement() {
        return typeOfManagement;
    }

    /**
     * Sets the value of the typeOfManagement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfManagement(String value) {
        this.typeOfManagement = value;
    }

    /**
     * Gets the value of the isFunctional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsFunctional() {
        return isFunctional;
    }

    /**
     * Sets the value of the isFunctional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsFunctional(String value) {
        this.isFunctional = value;
    }

    /**
     * Gets the value of the reasonNonFunctional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonNonFunctional() {
        return reasonNonFunctional;
    }

    /**
     * Sets the value of the reasonNonFunctional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonNonFunctional(String value) {
        this.reasonNonFunctional = value;
    }

    /**
     * Gets the value of the daysNonFuntional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysNonFuntional() {
        return daysNonFuntional;
    }

    /**
     * Sets the value of the daysNonFuntional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysNonFuntional(String value) {
        this.daysNonFuntional = value;
    }

    /**
     * Gets the value of the hasPreviousRepairs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasPreviousRepairs() {
        return hasPreviousRepairs;
    }

    /**
     * Sets the value of the hasPreviousRepairs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasPreviousRepairs(String value) {
        this.hasPreviousRepairs = value;
    }

    /**
     * Gets the value of the lastRepairDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastRepairDate() {
        return lastRepairDate;
    }

    /**
     * Sets the value of the lastRepairDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastRepairDate(String value) {
        this.lastRepairDate = value;
    }

    /**
     * Gets the value of the hasMinorService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasMinorService() {
        return hasMinorService;
    }

    /**
     * Sets the value of the hasMinorService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasMinorService(String value) {
        this.hasMinorService = value;
    }

    /**
     * Gets the value of the hasMajorService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasMajorService() {
        return hasMajorService;
    }

    /**
     * Sets the value of the hasMajorService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasMajorService(String value) {
        this.hasMajorService = value;
    }

    /**
     * Gets the value of the dateLastRepair property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastRepair() {
        return dateLastRepair;
    }

    /**
     * Sets the value of the dateLastRepair property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastRepair(String value) {
        this.dateLastRepair = value;
    }

    /**
     * Gets the value of the isWucEstablished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWucEstablished() {
        return isWucEstablished;
    }

    /**
     * Sets the value of the isWucEstablished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWucEstablished(String value) {
        this.isWucEstablished = value;
    }

    /**
     * Gets the value of the isWucFunctional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWucFunctional() {
        return isWucFunctional;
    }

    /**
     * Sets the value of the isWucFunctional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWucFunctional(String value) {
        this.isWucFunctional = value;
    }

    /**
     * Gets the value of the isWucTrained property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsWucTrained() {
        return isWucTrained;
    }

    /**
     * Sets the value of the isWucTrained property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsWucTrained(String value) {
        this.isWucTrained = value;
    }

    /**
     * Gets the value of the membersNumberWuc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMembersNumberWuc() {
        return membersNumberWuc;
    }

    /**
     * Sets the value of the membersNumberWuc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMembersNumberWuc(String value) {
        this.membersNumberWuc = value;
    }

    /**
     * Gets the value of the womenNumberWuc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWomenNumberWuc() {
        return womenNumberWuc;
    }

    /**
     * Sets the value of the womenNumberWuc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWomenNumberWuc(String value) {
        this.womenNumberWuc = value;
    }

    /**
     * Gets the value of the womenKeypositionsNumberWuc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWomenKeypositionsNumberWuc() {
        return womenKeypositionsNumberWuc;
    }

    /**
     * Sets the value of the womenKeypositionsNumberWuc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWomenKeypositionsNumberWuc(String value) {
        this.womenKeypositionsNumberWuc = value;
    }

}
