package org.m4water.server.admin.model;
// Generated Sep 15, 2011 12:10:51 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inspection generated by hbm2java
 */
public class Inspection  extends AbstractEditable{


     private String ispectionId;
     private Waterpoint waterpoint;
     private String inspectorName;
     private String inspectorTitle;
     private Date inspectionDate;
     private Set inspectionQuestionses = new HashSet(0);

    public Inspection() {
    }

	
    public Inspection(String id) {
        this.ispectionId = id;
    }
    public Inspection(String id, Waterpoint waterpoint, String inspectorName, String inspectorTitle, Date inspectionDate, Set inspectionQuestionses) {
       this.ispectionId = id;
       this.waterpoint = waterpoint;
       this.inspectorName = inspectorName;
       this.inspectorTitle = inspectorTitle;
       this.inspectionDate = inspectionDate;
       this.inspectionQuestionses = inspectionQuestionses;
    }
   
    public String getInspectionId() {
        return this.ispectionId;
    }
    
    public void setInspectionId(String id) {
        this.ispectionId = id;
    }
    public Waterpoint getWaterpoint() {
        return this.waterpoint;
    }
    
    public void setWaterpoint(Waterpoint waterpoint) {
        this.waterpoint = waterpoint;
    }
    public String getInspectorName() {
        return this.inspectorName;
    }
    
    public void setInspectorName(String inspectorName) {
        this.inspectorName = inspectorName;
    }
    public String getInspectorTitle() {
        return this.inspectorTitle;
    }
    
    public void setInspectorTitle(String inspectorTitle) {
        this.inspectorTitle = inspectorTitle;
    }
    public Date getInspectionDate() {
        return this.inspectionDate;
    }
    
    public void setInspectionDate(Date inspectionDate) {
        this.inspectionDate = inspectionDate;
    }
    public Set getInspectionQuestionses() {
        return this.inspectionQuestionses;
    }
    
    public void setInspectionQuestionses(Set inspectionQuestionses) {
        this.inspectionQuestionses = inspectionQuestionses;
    }




}


