package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ProblemLog generated by hbm2java
 */
public class ProblemLog  extends AbstractEditable <Integer> {


     
     private Problem problem;
     private String senderNo;
     private Date date;
     private String issue;

    public ProblemLog() {
    }

    public ProblemLog(int logId, Problem problem, String senderNo, Date date, String issue) {
       this.id = logId;
       this.problem = problem;
       this.senderNo = senderNo;
       this.date = date;
       this.issue = issue;
    }
   
    public int getLogId() {
        return this.id;
    }
    
    public void setLogId(int logId) {
        this.id = logId;
    }
    public Problem getProblem() {
        return this.problem;
    }
    
    public void setProblem(Problem problem) {
        this.problem = problem;
    }
    public String getSenderNo() {
        return this.senderNo;
    }
    
    public void setSenderNo(String senderNo) {
        this.senderNo = senderNo;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getIssue() {
        return this.issue;
    }
    
    public void setIssue(String issue) {
        this.issue = issue;
    }




}


