package org.m4water.server.admin.model;
// Generated Sep 18, 2011 5:57:04 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subcounty generated by hbm2java
 */
public class Subcounty  extends AbstractEditable<String> {


     
     private County county;
     private String subcountyId;
     private String subcountyName;
     private String boundaryData;
     private Set<User> users = new HashSet<User>(0);

    public Subcounty() {
    }

	
    public Subcounty(String id, County county, String subcountyName, String boundaryData) {
        this.id = id;
        this.county = county;
        this.subcountyName = subcountyName;
        this.boundaryData = boundaryData;
    }
    public Subcounty(String id, County county, String subcountyName, String boundaryData, Set<User> users) {
       this.id= id;
       this.county = county;
       this.subcountyName = subcountyName;
       this.boundaryData = boundaryData;
       this.users = users;
    }
   
    public String getSubcountyId() {
        return this.subcountyId;
    }
    
  
    public County getCounty() {
        return this.county;
    }
    
    public void setCounty(County county) {
        this.county = county;
    }
    public String getSubcountyName() {
        return this.subcountyName;
    }
    
    public void setSubcountyName(String subcountyName) {
        this.subcountyName = subcountyName;
    }
    public String getBoundaryData() {
        return this.boundaryData;
    }
    
    public void setBoundaryData(String boundaryData) {
        this.boundaryData = boundaryData;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

    public void setSubcountyId(String subcounty_id) {
        this.subcountyId = subcounty_id;
    }
    
    




}


