package org.m4water.server.admin.model;
// Generated Sep 18, 2011 5:57:04 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Subcounty generated by hbm2java
 */
public class Subcounty extends AbstractEditable<String> {

    private County county;
    private String subcountyId;
    private String subcountyName;
    private String boundaryData;
    private Set<User> users = new HashSet<User>(0);
    private Set<Parish> parishs = new HashSet<Parish>(0);

    public Subcounty() {
    }

    public Subcounty(String id, County county, String subcountyId, String subcountyName, String boundaryData) {
        this.id = id;
        this.county = county;
        this.subcountyId = subcountyId;
        this.subcountyName = subcountyName;
        this.boundaryData = boundaryData;
    }

    public Subcounty(String id, County county, String subcountyId, String subcountyName, String boundaryData, Set<User> users, Set parishs) {
        this.id = id;
        this.county = county;
        this.subcountyId = subcountyId;
        this.subcountyName = subcountyName;
        this.boundaryData = boundaryData;
        this.users = users;
        this.parishs = parishs;
    }

    public String getSubcountyId() {
        return this.subcountyId;
    }

    public County getCounty() {
        return this.county;
    }

    public void setCounty(County county) {
        this.county = county;
    }

    public String getSubcountyName() {
        return this.subcountyName;
    }

    public void setSubcountyName(String subcountyName) {
        this.subcountyName = subcountyName;
    }

    public String getBoundaryData() {
        return this.boundaryData;
    }

    public void setBoundaryData(String boundaryData) {
        this.boundaryData = boundaryData;
    }

    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }

    public void setSubcountyId(String subcounty_id) {
        this.subcountyId = subcounty_id;
    }

    public Set getParishs() {
        return this.parishs;
    }

    public void setParishs(Set parishs) {
        this.parishs = parishs;
    }

    public Village getVillage(String village) {
        for (Parish parish : parishs) {
            Set villages = parish.getVillages();
            for (Object object : villages) {
                Village vill = (Village) object;
                if (vill.getVillagename() != null && vill.getVillagename().equalsIgnoreCase(village))
                    return vill;
            }
        }
        return null;
    }
}
