package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Subcounty generated by hbm2java
 */
public class Subcounty  extends AbstractEditable {


     private String subcountyId;
     private County county;
     private String subcountyName;
     private String boundaryData;
     private Set parishs = new HashSet(0);

    public Subcounty() {
    }

	
    public Subcounty(String subcountyId, County county, String subcountyName, String boundaryData) {
        this.subcountyId = subcountyId;
        this.county = county;
        this.subcountyName = subcountyName;
        this.boundaryData = boundaryData;
    }
    public Subcounty(String subcountyId, County county, String subcountyName, String boundaryData, Set parishs) {
       this.subcountyId = subcountyId;
       this.county = county;
       this.subcountyName = subcountyName;
       this.boundaryData = boundaryData;
       this.parishs = parishs;
    }
   
    public String getSubcountyId() {
        return this.subcountyId;
    }
    
    public void setSubcountyId(String subcountyId) {
        this.subcountyId = subcountyId;
    }
    public County getCounty() {
        return this.county;
    }
    
    public void setCounty(County county) {
        this.county = county;
    }
    public String getSubcountyName() {
        return this.subcountyName;
    }
    
    public void setSubcountyName(String subcountyName) {
        this.subcountyName = subcountyName;
    }
    public String getBoundaryData() {
        return this.boundaryData;
    }
    
    public void setBoundaryData(String boundaryData) {
        this.boundaryData = boundaryData;
    }
    public Set getParishs() {
        return this.parishs;
    }
    
    public void setParishs(Set parishs) {
        this.parishs = parishs;
    }




}


