package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserAssigned generated by hbm2java
 */
public class UserAssigned  extends AbstractEditable {


     private UserAssignedId userAssignedId;
     private User user;
     private Problem problem;
     private Date dateAssigned;

    public UserAssigned() {
    }

    public UserAssigned(UserAssignedId id, User user, Problem problem, Date dateAssigned) {
       this.userAssignedId = id;
       this.user = user;
       this.problem = problem;
       this.dateAssigned = dateAssigned;
    }
   
    public UserAssignedId getUserAssignedId() {
        return this.userAssignedId;
    }
    
    public void setId(UserAssignedId id) {
        this.userAssignedId = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Problem getProblem() {
        return this.problem;
    }
    
    public void setProblem(Problem problem) {
        this.problem = problem;
    }
    public Date getDateAssigned() {
        return this.dateAssigned;
    }
    
    public void setDateAssigned(Date dateAssigned) {
        this.dateAssigned = dateAssigned;
    }




}


