package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  extends AbstractEditable {


     private String userId;
     private String firstname;
     private String lastname;
     private String contacts;
     private String password;
     private String staffProfileId;
     private String subcountyId;
     private Set userAssigneds = new HashSet(0);

    public User() {
    }

	
    public User(String userId, String firstname, String lastname, String contacts, String password, String staffProfileId, String subcountyId) {
        this.userId = userId;
        this.firstname = firstname;
        this.lastname = lastname;
        this.contacts = contacts;
        this.password = password;
        this.staffProfileId = staffProfileId;
        this.subcountyId = subcountyId;
    }
    public User(String userId, String firstname, String lastname, String contacts, String password, String staffProfileId, String subcountyId, Set userAssigneds) {
       this.userId = userId;
       this.firstname = firstname;
       this.lastname = lastname;
       this.contacts = contacts;
       this.password = password;
       this.staffProfileId = staffProfileId;
       this.subcountyId = subcountyId;
       this.userAssigneds = userAssigneds;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getContacts() {
        return this.contacts;
    }
    
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStaffProfileId() {
        return this.staffProfileId;
    }
    
    public void setStaffProfileId(String staffProfileId) {
        this.staffProfileId = staffProfileId;
    }
    public String getSubcountyId() {
        return this.subcountyId;
    }
    
    public void setSubcountyId(String subcountyId) {
        this.subcountyId = subcountyId;
    }
    public Set getUserAssigneds() {
        return this.userAssigneds;
    }
    
    public void setUserAssigneds(Set userAssigneds) {
        this.userAssigneds = userAssigneds;
    }




}


