package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Village generated by hbm2java
 */
public class Village  extends AbstractEditable {


     private String villageId;
     private Parish parish;
     private String villagename;
     private Set waterpoints = new HashSet(0);

    public Village() {
    }

	
    public Village(String villageId, Parish parish, String villagename) {
        this.villageId = villageId;
        this.parish = parish;
        this.villagename = villagename;
    }
    public Village(String villageId, Parish parish, String villagename, Set waterpoints) {
       this.villageId = villageId;
       this.parish = parish;
       this.villagename = villagename;
       this.waterpoints = waterpoints;
    }
   
    public String getVillageId() {
        return this.villageId;
    }
    
    public void setVillageId(String villageId) {
        this.villageId = villageId;
    }
    public Parish getParish() {
        return this.parish;
    }
    
    public void setParish(Parish parish) {
        this.parish = parish;
    }
    public String getVillagename() {
        return this.villagename;
    }
    
    public void setVillagename(String villagename) {
        this.villagename = villagename;
    }
    public Set getWaterpoints() {
        return this.waterpoints;
    }
    
    public void setWaterpoints(Set waterpoints) {
        this.waterpoints = waterpoints;
    }




}


