package org.m4water.server.admin.model;
// Generated Aug 26, 2011 5:58:15 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Waterpoint generated by hbm2java
 */
public class Waterpoint  extends AbstractEditable {

     private String referenceNumber;
     private Date date;
     private String district;
     private String subcounty;
     private String village;
     private String latitude;
     private String longitude;
     private String waterSourceType;
     private Set tickets = new HashSet(0);

    public Waterpoint() {
    }

	
    public Waterpoint(int id, String referenceNumber, Date date, String district, String subcounty, String village, String latitude, String longitude, String waterSourceType) {
        this.id = id;
        this.referenceNumber = referenceNumber;
        this.date = date;
        this.district = district;
        this.subcounty = subcounty;
        this.village = village;
        this.latitude = latitude;
        this.longitude = longitude;
        this.waterSourceType = waterSourceType;
    }
    public Waterpoint(int id, String referenceNumber, Date date, String district, String subcounty, String village, String latitude, String longitude, String waterSourceType, Set tickets) {
       this.id = id;
       this.referenceNumber = referenceNumber;
       this.date = date;
       this.district = district;
       this.subcounty = subcounty;
       this.village = village;
       this.latitude = latitude;
       this.longitude = longitude;
       this.waterSourceType = waterSourceType;
       this.tickets = tickets;
    }
   
   
    @Override
    public void setId(int id) {
        this.id = id;
    }
    public String getReferenceNumber() {
        return this.referenceNumber;
    }
    
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }
    public String getSubcounty() {
        return this.subcounty;
    }
    
    public void setSubcounty(String subcounty) {
        this.subcounty = subcounty;
    }
    public String getVillage() {
        return this.village;
    }
    
    public void setVillage(String village) {
        this.village = village;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getWaterSourceType() {
        return this.waterSourceType;
    }
    
    public void setWaterSourceType(String waterSourceType) {
        this.waterSourceType = waterSourceType;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }




}


