package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * WaterFunctionality generated by hbm2java
 */
public class WaterFunctionality  extends AbstractEditable<String> {


     private Waterpoint waterpoint;
     private String functionalityStatus;
     private Date dateNonFunctional;
     private String reason;
     private Date dateLastRepaired;
     private String detailsLastRepair;
     private Date dateLastMinorService;
     private Date dateLastMajorService;
     private String anyPreviousRepairs;
     private String anyPreviousMinorService;
     private String anyPreviousMajorService;
     private Date date;

    public WaterFunctionality() {
    }

    public WaterFunctionality(Date date, Waterpoint waterpoint, String functionalityStatus, Date dayNonFunctional, String reason, Date dateLastRepaired, String detailsLastRepair, Date dateLastMinorService, Date dateLastMajorService, String anyPreviousRepairs, String anyPreviousMinorService, String anyPreviousMajorService) {
       this.date = date;
       this.waterpoint = waterpoint;
       this.functionalityStatus = functionalityStatus;
       this.dateNonFunctional = dayNonFunctional;
       this.reason = reason;
       this.dateLastRepaired = dateLastRepaired;
       this.detailsLastRepair = detailsLastRepair;
       this.dateLastMinorService = dateLastMinorService;
       this.dateLastMajorService = dateLastMajorService;
       this.anyPreviousRepairs = anyPreviousRepairs;
       this.anyPreviousMinorService = anyPreviousMinorService;
       this.anyPreviousMajorService = anyPreviousMajorService;
    }
   
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Waterpoint getWaterpoint() {
        return this.waterpoint;
    }
    
    public void setWaterpoint(Waterpoint waterpoint) {
        this.waterpoint = waterpoint;
    }
    public String getFunctionalityStatus() {
        return this.functionalityStatus;
    }
    
    public void setFunctionalityStatus(String functionalityStatus) {
        this.functionalityStatus = functionalityStatus;
    }
    public Date getDateNonFunctional() {
        return this.dateNonFunctional;
    }

    public void setDateNonFunctional(Date dateNonFunctional) {
        this.dateNonFunctional = dateNonFunctional;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Date getDateLastRepaired() {
        return this.dateLastRepaired;
    }
    
    public void setDateLastRepaired(Date dateLastRepaired) {
        this.dateLastRepaired = dateLastRepaired;
    }
    public String getDetailsLastRepair() {
        return this.detailsLastRepair;
    }
    
    public void setDetailsLastRepair(String detailsLastRepair) {
        this.detailsLastRepair = detailsLastRepair;
    }
    public Date getDateLastMinorService() {
        return this.dateLastMinorService;
    }
    
    public void setDateLastMinorService(Date dateLastMinorService) {
        this.dateLastMinorService = dateLastMinorService;
    }
    public Date getDateLastMajorService() {
        return this.dateLastMajorService;
    }
    
    public void setDateLastMajorService(Date dateLastMajorService) {
        this.dateLastMajorService = dateLastMajorService;
    }    public String getAnyPreviousRepairs() {
        return this.anyPreviousRepairs;
    }

    public void setAnyPreviousRepairs(String anyPreviousRepairs) {
        this.anyPreviousRepairs = anyPreviousRepairs;
    }
    public String getAnyPreviousMinorService() {
        return this.anyPreviousMinorService;
    }

    public void setAnyPreviousMinorService(String anyPreviousMinorService) {
        this.anyPreviousMinorService = anyPreviousMinorService;
    }
    public String getAnyPreviousMajorService() {
        return this.anyPreviousMajorService;
    }

    public void setAnyPreviousMajorService(String anyPreviousMajorService) {
        this.anyPreviousMajorService = anyPreviousMajorService;
    }




}


