package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA



/**
 * WaterUserCommittee generated by hbm2java
 */
public class WaterUserCommittee  extends AbstractEditable<String> {


     
     private Waterpoint waterpoint;
     private String commissioned;
     private String yrEstablished;
     private String trained;
     private String collectFees;
     private String regularService;
     private String regularMeeting;
     private String noActiveMembers;
     private String noOfWomen;
     private String noOfWomenKeypos;

    public WaterUserCommittee() {
    }

    public WaterUserCommittee(String userCommitteeId, Waterpoint waterpoint, String commissioned, String yrEstablished, String trained, String collectFees, String regularService, String regularMeeting, String noActiveMembers, String noOfWomen, String noOfWomenKeypos) {
       this.id = userCommitteeId;
       this.waterpoint = waterpoint;
       this.commissioned = commissioned;
       this.yrEstablished = yrEstablished;
       this.trained = trained;
       this.collectFees = collectFees;
       this.regularService = regularService;
       this.regularMeeting = regularMeeting;
       this.noActiveMembers = noActiveMembers;
       this.noOfWomen = noOfWomen;
       this.noOfWomenKeypos = noOfWomenKeypos;
    }
   
    public String getUserCommitteeId() {
        return this.id;
    }
    
    public void setUserCommitteeId(String userCommitteeId) {
        this.id = userCommitteeId;
    }
    public Waterpoint getWaterpoint() {
        return this.waterpoint;
    }
    
    public void setWaterpoint(Waterpoint waterpoint) {
        this.waterpoint = waterpoint;
    }
    public String getCommissioned() {
        return this.commissioned;
    }
    
    public void setCommissioned(String commissioned) {
        this.commissioned = commissioned;
    }
    public String getYrEstablished() {
        return this.yrEstablished;
    }
    
    public void setYrEstablished(String yrEstablished) {
        this.yrEstablished = yrEstablished;
    }
    public String getTrained() {
        return this.trained;
    }
    
    public void setTrained(String trained) {
        this.trained = trained;
    }
    public String getCollectFees() {
        return this.collectFees;
    }
    
    public void setCollectFees(String collectFees) {
        this.collectFees = collectFees;
    }
    public String getRegularService() {
        return this.regularService;
    }
    
    public void setRegularService(String regularService) {
        this.regularService = regularService;
    }
    public String getRegularMeeting() {
        return this.regularMeeting;
    }
    
    public void setRegularMeeting(String regularMeeting) {
        this.regularMeeting = regularMeeting;
    }
    public String getNoActiveMembers() {
        return this.noActiveMembers;
    }
    
    public void setNoActiveMembers(String noActiveMembers) {
        this.noActiveMembers = noActiveMembers;
    }
    public String getNoOfWomen() {
        return this.noOfWomen;
    }
    
    public void setNoOfWomen(String noOfWomen) {
        this.noOfWomen = noOfWomen;
    }
    public String getNoOfWomenKeypos() {
        return this.noOfWomenKeypos;
    }
    
    public void setNoOfWomenKeypos(String noOfWomenKeypos) {
        this.noOfWomenKeypos = noOfWomenKeypos;
    }




}


