package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * WaterpointTypes generated by hbm2java
 */
public class WaterpointTypes  extends AbstractEditable<Integer> {


     private int typeId;
     private String name;
     private Set waterpoints = new HashSet(0);

    public WaterpointTypes() {
    }

	
    public WaterpointTypes(int typeId, String name) {
        this.typeId = typeId;
        this.name = name;
    }
    public WaterpointTypes(int typeId, String name, Set waterpoints) {
       this.typeId = typeId;
       this.name = name;
       this.waterpoints = waterpoints;
    }
   
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getWaterpoints() {
        return this.waterpoints;
    }
    
    public void setWaterpoints(Set waterpoints) {
        this.waterpoints = waterpoints;
    }

}


