package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * County generated by hbm2java
 */
public class County  extends AbstractEditable<String> {


     
     private District district;
     private String countyName;
     private String boundaryData;
     private Set subcounties = new HashSet(0);

    public County() {
    }

	
    public County(String id, District district, String countyName, String boundaryData) {
        this.id = id;
        this.district = district;
        this.countyName = countyName;
        this.boundaryData = boundaryData;
    }
    public County(String id, District district, String countyName, String boundaryData, Set subcounties) {
       this.id = id;
       this.district = district;
       this.countyName = countyName;
       this.boundaryData = boundaryData;
       this.subcounties = subcounties;
    }
   
    public String getid() {
        return this.id;
    }
    
    public void setid(String id) {
        this.id = id;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getCountyName() {
        return this.countyName;
    }
    
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }
    public String getBoundaryData() {
        return this.boundaryData;
    }
    
    public void setBoundaryData(String boundaryData) {
        this.boundaryData = boundaryData;
    }
    public Set getSubcounties() {
        return this.subcounties;
    }
    
    public void setSubcounties(Set subcounties) {
        this.subcounties = subcounties;
    }




}


