package org.m4water.server.admin.model;
// Generated Sep 7, 2011 12:43:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Parish generated by hbm2java
 */
public class Parish  extends AbstractEditable<String> {


     private String parishId;
     private Subcounty subcounty;
     private String parishName;
     private String boundaryData;
     private Set villages = new HashSet(0);

    public Parish() {
    }

	
    public Parish(String parishId, Subcounty subcounty, String parishName, String boundaryData) {
        this.parishId = parishId;
        this.subcounty = subcounty;
        this.parishName = parishName;
        this.boundaryData = boundaryData;
    }
    public Parish(String parishId, Subcounty subcounty, String parishName, String boundaryData, Set villages) {
       this.parishId = parishId;
       this.subcounty = subcounty;
       this.parishName = parishName;
       this.boundaryData = boundaryData;
       this.villages = villages;
    }

    public String getParishId() {
        return this.parishId;
    }

    public void setParishId(String parishId) {
        this.parishId = parishId;
    }
    public Subcounty getSubcounty() {
        return this.subcounty;
    }
    
    public void setSubcounty(Subcounty subcounty) {
        this.subcounty = subcounty;
    }
    public String getParishName() {
        return this.parishName;
    }
    
    public void setParishName(String parishName) {
        this.parishName = parishName;
    }
    public String getBoundaryData() {
        return this.boundaryData;
    }
    
    public void setBoundaryData(String boundaryData) {
        this.boundaryData = boundaryData;
    }
    public Set getVillages() {
        return this.villages;
    }
    
    public void setVillages(Set villages) {
        this.villages = villages;
    }




}


