package org.m4water.server.admin.model;
// Generated Aug 26, 2011 5:58:15 PM by Hibernate Tools 3.2.1.GA



/**
 * User generated by hbm2java
 */
public class User  extends AbstractEditable {


     private Integer userId;
     private String fname;
     private String lname;
     private String email;
     private String telephone;
     private String username;
     private String password;

    public User() {
    }

    public User(String fname, String lname, String email, String telephone, String username, String password) {
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.telephone = telephone;
       this.username = username;
       this.password = password;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


