package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA



/**
 * UserAssignedId generated by hbm2java
 */
public class UserAssignedId  extends AbstractEditable {


     private String userId;
     private int problemId;

    public UserAssignedId() {
    }

    public UserAssignedId(String userId, int problemId) {
       this.userId = userId;
       this.problemId = problemId;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public int getProblemId() {
        return this.problemId;
    }
    
    public void setProblemId(int problemId) {
        this.problemId = problemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserAssignedId) ) return false;
		 UserAssignedId castOther = ( UserAssignedId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && (this.getProblemId()==castOther.getProblemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + this.getProblemId();
         return result;
   }   


}


