package org.m4water.server.admin.model;
// Generated Sep 7, 2011 11:37:27 AM by Hibernate Tools 3.2.1.GA



/**
 * WaterUserCommittee generated by hbm2java
 */
public class WaterUserCommittee  extends AbstractEditable<String> {


     
     private Waterpoint waterpoint;
     private String commissioned;
     private String yrEstablished;
     private String trained;
     private String noActiveMembers;
     private String noOfWomen;
     private String noOfWomenKeypos;
     private String noOfMembersOnWuc;
     private String functionalityOfWuc;

    public WaterUserCommittee() {
    }

    public WaterUserCommittee(String userCommitteeId, Waterpoint waterpoint, String commissioned, String yrEstablished, String trained, String noActiveMembers, String noOfWomen, String noOfWomenKeypos, String noOfMembersOnWuc, String functionalityOfWuc) {
       this.id = userCommitteeId;
       this.waterpoint = waterpoint;
       this.commissioned = commissioned;
       this.yrEstablished = yrEstablished;
       this.trained = trained;
       this.noActiveMembers = noActiveMembers;
       this.noOfWomen = noOfWomen;
       this.noOfWomenKeypos = noOfWomenKeypos;
       this.noOfMembersOnWuc = noOfMembersOnWuc;
       this.functionalityOfWuc = functionalityOfWuc;
    }
   
    public String getUserCommitteeId() {
        return this.id;
    }
    
    public void setUserCommitteeId(String userCommitteeId) {
        this.id = userCommitteeId;
    }
    public Waterpoint getWaterpoint() {
        return this.waterpoint;
    }
    
    public void setWaterpoint(Waterpoint waterpoint) {
        this.waterpoint = waterpoint;
    }
    public String getCommissioned() {
        return this.commissioned;
    }
    
    public void setCommissioned(String commissioned) {
        this.commissioned = commissioned;
    }
    public String getYrEstablished() {
        return this.yrEstablished;
    }
    
    public void setYrEstablished(String yrEstablished) {
        this.yrEstablished = yrEstablished;
    }
    public String getTrained() {
        return this.trained;
    }
    
    public void setTrained(String trained) {
        this.trained = trained;
    }
    public String getNoActiveMembers() {
        return this.noActiveMembers;
    }
    
    public void setNoActiveMembers(String noActiveMembers) {
        this.noActiveMembers = noActiveMembers;
    }
    public String getNoOfWomen() {
        return this.noOfWomen;
    }
    
    public void setNoOfWomen(String noOfWomen) {
        this.noOfWomen = noOfWomen;
    }
    public String getNoOfWomenKeypos() {
        return this.noOfWomenKeypos;
    }
    
    public void setNoOfWomenKeypos(String noOfWomenKeypos) {
        this.noOfWomenKeypos = noOfWomenKeypos;
    }
    public String getNoOfMembersOnWuc() {
        return this.noOfMembersOnWuc;
    }

    public void setNoOfMembersOnWuc(String noOfMembersOnWuc) {
        this.noOfMembersOnWuc = noOfMembersOnWuc;
    }
    public String getFunctionalityOfWuc() {
        return this.functionalityOfWuc;
    }

    public void setFunctionalityOfWuc(String functionalityOfWuc) {
        this.functionalityOfWuc = functionalityOfWuc;
    }




}


